"""Records that flow between pipeline stages (one JSONL file per stage in the run directory)."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field

from distillery.schema import TicketTriage


class RawTicket(BaseModel):
    """An unlabeled input: generated by the teacher or imported from real data."""

    id: str
    text: str
    source: Literal["synthetic", "imported"] = "synthetic"
    seed: dict[str, Any] | None = None
    generator_model: str | None = None


class TeacherLabel(BaseModel):
    """One teacher's answer for one ticket."""

    model: str
    triage: TicketTriage | None = None
    error: str | None = None
    repaired: bool = False


class LabeledTicket(BaseModel):
    id: str
    text: str
    source: Literal["synthetic", "imported"] = "synthetic"
    seed: dict[str, Any] | None = None
    labels: list[TeacherLabel] = Field(default_factory=list)


class Example(BaseModel):
    """A clean training example after filtering."""

    id: str
    text: str
    triage: TicketTriage
    source: Literal["synthetic", "imported"] = "synthetic"


class DroppedExample(BaseModel):
    id: str
    stage: str
    reason: str
    text: str


class FunnelStep(BaseModel):
    name: str
    description: str
    kept: int
    dropped: int = 0
    modified: int = 0
    reasons: dict[str, int] = Field(default_factory=dict)


class GoldItem(BaseModel):
    """A hand-written, hand-labeled test ticket (never produced by a teacher)."""

    id: str
    text: str
    label: TicketTriage
    note: str | None = None


class RunPaths(BaseModel):
    """File layout of one pipeline run directory."""

    root: Path
    # Optional shared dataset location (e.g. a committed dataset trained on a GPU elsewhere).
    dataset_override: Path | None = None

    @property
    def generated(self) -> Path:
        return self.root / "generated.jsonl"

    @property
    def generation(self) -> Path:
        return self.root / "generation.json"

    @property
    def labeled(self) -> Path:
        return self.root / "labeled.jsonl"

    @property
    def filtered(self) -> Path:
        return self.root / "filtered.jsonl"

    @property
    def dropped(self) -> Path:
        return self.root / "dropped.jsonl"

    @property
    def funnel(self) -> Path:
        return self.root / "funnel.json"

    @property
    def label_stats(self) -> Path:
        return self.root / "label_stats.json"

    @property
    def dataset_dir(self) -> Path:
        return self.dataset_override or self.root / "dataset"

    @property
    def train(self) -> Path:
        return self.dataset_dir / "train.jsonl"

    @property
    def val(self) -> Path:
        return self.dataset_dir / "val.jsonl"

    @property
    def dataset_stats(self) -> Path:
        return self.dataset_dir / "stats.json"

    @property
    def dataset_card(self) -> Path:
        return self.dataset_dir / "README.md"

    @property
    def adapter_dir(self) -> Path:
        return self.root / "student" / "adapter"

    @property
    def merged_dir(self) -> Path:
        return self.root / "student" / "merged"

    @property
    def train_metrics(self) -> Path:
        return self.root / "student" / "train_metrics.json"

    @property
    def eval_dir(self) -> Path:
        return self.root / "eval"

    @property
    def eval_report(self) -> Path:
        return self.eval_dir / "report.json"

    @property
    def calls(self) -> Path:
        return self.root / "calls.jsonl"

    @property
    def report_html(self) -> Path:
        return self.root / "report.html"

    def predictions(self, system: str) -> Path:
        return self.eval_dir / f"predictions_{system}.jsonl"
